# Generated by Django 5.0.4 on 2024-04-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_categoria_estoque_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria'),
        ),
    ]
