# Generated by Django 5.0.4 on 2024-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_estoque_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhaimagem',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
